Use distro tools for dealing with enabling/creating package repos (when permitted). Refs alces-software/clusterware#70.

diff --git a/chrome/metadata.yml b/chrome/metadata.yml
--- a/chrome/metadata.yml
+++ b/chrome/metadata.yml
@@ -1,7 +1,24 @@
 ---
 install:
   el7: |
-    cat <<\EOF > /etc/yum.repos.d/google-chrome.repo
+    require files
+    files_load_config clusterware
+    case "${cw_VERSION:-1.0.0}" in
+      1.[0-4].*)
+          echo "This session cannot be enabled as Alces Clusterware v${cw_VERSION} is too old."
+          echo "Please upgrade to Alces Clusterware v1.5.0 or higher."
+          exit 1
+          ;;
+    esac
+
+    require distro
+    if distro_is_repository_permitted google-chrome; then
+      if ! distro_repository_exists google-chrome; then      
+        cat <<\REPO > "${cw_ROOT}"/etc/distro/repos/google-chrome.sh
+    #!/bin/bash
+    if [ "$1" == "enable" ]; then
+        if [ ! -f /etc/yum.repos.d/google-chrome.repo ]; then
+            cat <<\EOF > /etc/yum.repos.d/google-chrome.repo
     [google-chrome]
     name=google-chrome
     baseurl=http://dl.google.com/linux/chrome/rpm/stable/$basearch
@@ -9,7 +26,23 @@ install:
     gpgcheck=1
     gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
     EOF
-    yum -e0 -y install google-chrome-stable
+        fi
+    else
+        rm -f /etc/yum.repos.d/google-chrome.repo
+    fi
+    REPO
+        chmod 755 "${cw_ROOT}"/etc/distro/repos/google-chrome.sh
+      fi
+      if distro_enable_repository google-chrome; then
+        yum -e0 -y install google-chrome-stable
+      else
+        echo "Sorry, the Google Chrome repository is not available."
+        exit 1
+      fi
+    else
+      echo "Sorry, the Google Chrome repository is prohibited."
+      exit 1
+    fi
   el6: |
     echo "Sorry, the Google Chrome Browser session is not currently available in EL6 distributions as Google Chrome support for EL6 has been discontinued."
     exit 1
diff --git a/icewm/metadata.yml b/icewm/metadata.yml
--- a/icewm/metadata.yml
+++ b/icewm/metadata.yml
@@ -1,10 +1,40 @@
 ---
 install:
   el7: |
-    yum -e0 -y install epel-release
-    yum -e0 -y install icewm
-    yum -e0 -y install evince
+    require files
+    files_load_config clusterware
+    case "${cw_VERSION:-1.0.0}" in
+      1.[0-4].*)
+          echo "This session cannot be enabled as Alces Clusterware v${cw_VERSION} is too old."
+          echo "Please upgrade to Alces Clusterware v1.5.0 or higher."
+          exit 1
+          ;;
+    esac
+
+    require distro
+    if distro_enable_repository epel; then
+      yum -e0 -y install icewm
+      yum -e0 -y install evince
+    else
+      echo "Sorry, the EPEL repository is not available."
+      exit 1
+    fi
   el6: |
-    yum -e0 -y install epel-release
-    yum -e0 -y install icewm
-    yum -e0 -y install evince
+    require files
+    files_load_config clusterware
+    case "${cw_VERSION:-1.0.0}" in
+      1.[0-4].*)
+          echo "This session cannot be enabled as Alces Clusterware v${cw_VERSION} is too old."
+          echo "Please upgrade to Alces Clusterware v1.5.0 or higher."
+          exit 1
+          ;;
+    esac
+
+    require distro
+    if distro_enable_repository epel; then
+      yum -e0 -y install icewm
+      yum -e0 -y install evince
+    else
+      echo "Sorry, the EPEL repository is not available."
+      exit 1
+    fi
diff --git a/trinity/metadata.yml b/trinity/metadata.yml
--- a/trinity/metadata.yml
+++ b/trinity/metadata.yml
@@ -1,10 +1,72 @@
 ---
 install:
   el7: |
-    yum install -y http://mirror.ppa.trinitydesktop.org/trinity/trinity/rpm/el7/trinity-r14/RPMS/noarch/trinity-repo-14.0.2-1.el7.noarch.rpm
-    yum install -y ftp://ftp.pbone.net/mirror/atrpms.net/el7-x86_64/atrpms/stable/libmad-0.15.1b-4.el7.x86_64.rpm
-    yum install -y trinity-tdebase
+    require files
+    files_load_config clusterware
+    case "${cw_VERSION:-1.0.0}" in
+      1.[0-4].*)
+          echo "This session cannot be enabled as Alces Clusterware v${cw_VERSION} is too old."
+          echo "Please upgrade to Alces Clusterware v1.5.0 or higher."
+          exit 1
+          ;;
+    esac
+
+    require distro
+    if distro_is_repository_permitted trinity; then
+      if ! distro_repository_exists trinity; then
+        cat <<\REPO > "${cw_ROOT}"/etc/distro/repos/trinity.sh
+    #!/bin/bash
+    if [ "$1" == "enable" ]; then
+      yum install -y http://mirror.ppa.trinitydesktop.org/trinity/trinity/rpm/el7/trinity-r14/RPMS/noarch/trinity-repo-14.0.2-1.el7.noarch.rpm
+    else
+      yum remove -y trinity-repo
+    fi
+    REPO
+        chmod 755 "${cw_ROOT}"/etc/distro/repos/trinity.sh
+      fi
+      if distro_enable_repository trinity; then
+        yum install -y ftp://ftp.pbone.net/mirror/atrpms.net/el7-x86_64/atrpms/stable/libmad-0.15.1b-4.el7.x86_64.rpm
+        yum install -y trinity-tdebase
+      else
+        echo "Sorry, the Trinity repository is not available."
+        exit 1
+      fi
+    else
+      echo "Sorry, the Trinity repository is prohibited."
+      exit 1
+    fi
   el6: |
-    yum install -y http://mirror.ppa.trinitydesktop.org/trinity/trinity/rpm/el6/trinity-r14/RPMS/noarch/trinity-repo-14.0.2-1.el6.noarch.rpm
-    yum install -y ftp://ftp.pbone.net/mirror/atrpms.net/el6-x86_64/atrpms/stable/libmad-0.15.1b-4.el6.x86_64.rpm
-    yum install -y trinity-tdebase
+    require files
+    files_load_config clusterware
+    case "${cw_VERSION:-1.0.0}" in
+      1.[0-4].*)
+          echo "This session cannot be enabled as Alces Clusterware v${cw_VERSION} is too old."
+          echo "Please upgrade to Alces Clusterware v1.5.0 or higher."
+          exit 1
+          ;;
+    esac
+
+    require distro
+    if distro_is_repository_permitted trinity; then
+      if ! distro_repository_exists trinity; then
+        cat <<\REPO > "${cw_ROOT}"/etc/distro/repos/trinity.sh
+    #!/bin/bash
+    if [ "$1" == "enable" ]; then
+      yum install -y http://mirror.ppa.trinitydesktop.org/trinity/trinity/rpm/el6/trinity-r14/RPMS/noarch/trinity-repo-14.0.2-1.el6.noarch.rpm
+    else
+      yum remove -y trinity-repo
+    fi
+    REPO
+        chmod 755 "${cw_ROOT}"/etc/distro/repos/trinity.sh
+      fi
+      if distro_enable_repository trinity; then
+        yum install -y ftp://ftp.pbone.net/mirror/atrpms.net/el6-x86_64/atrpms/stable/libmad-0.15.1b-4.el6.x86_64.rpm
+        yum install -y trinity-tdebase
+      else
+        echo "Sorry, the Trinity repository is not available."
+        exit 1
+      fi
+    else
+      echo "Sorry, the Trinity repository is prohibited."
+      exit 1
+    fi
